<a href="https://colab.research.google.com/github/VUKHACTAO/MH_2023/blob/main/Lab_6_20130399_VUKHACTAO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Na√Øve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**

# Import libraries

In [17]:

import pandas as pd
import numpy as np
from sklearn.datasets import fetch_openml
from keras.datasets import mnist
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer as sk
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.naive_bayes import GaussianNB 
from sklearn.datasets import fetch_openml
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score 
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import recall_score
from sklearn.datasets import load_iris
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn import svm
from google.colab import drive
from prettytable import PrettyTable
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/baitap'
from sklearn.utils.fixes import sklearn
from sklearn import metrics as m
from sklearn import tree 
from sklearn.model_selection import train_test_split as tts
from sklearn.neighbors import KNeighborsClassifier as knc
from sklearn import feature_selection
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest,chi2


from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/Lab_6'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
[Errno 2] No such file or directory: '/content/gdrive/MyDrive/baitap'
/content/gdrive/MyDrive/Lab_6
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
/content/gdrive/MyDrive/Lab_6

#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.

In [10]:
tb = PrettyTable()
tb.field_names = ["","Accuracy", "Precision", "F1", "Recall"]

In [11]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
tb.add_row(["GaussianNB", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

In [13]:
tb

In [14]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
clf = BernoulliNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
tb.add_row(["BernoulliNB", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

In [7]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
tb.add_row(["MultinomialNB", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

In [8]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
model = ComplementNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
tb.add_row(["ComplementNB", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

In [ ]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
tb.add_row(["Random Forest", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

+---------------+--------------------+--------------------+--------------------+--------------------+
|               |      Accuracy      |     Precision      |         F1         |       Recall       |
+---------------+--------------------+--------------------+--------------------+--------------------+
|   GaussianNB  | 0.6213492063492063 | 0.6947628629081618 | 0.5996090101442231 | 0.6177689510944427 |
|  BernoulliNB  | 0.8270952380952381 | 0.8283898184033166 | 0.8246061802516026 | 0.8238354941350515 |
| MultinomialNB | 0.8222698412698413 | 0.8295550165797616 | 0.8207947936585294 | 0.8190735039758186 |
|  ComplementNB | 0.7199523809523809 | 0.7501343819115547 | 0.7059257604811858 | 0.7130487776157894 |
| Random Forest | 0.942984126984127  | 0.9427272908414412 | 0.9423376144434009 | 0.942159515573975  |
+---------------+--------------------+--------------------+--------------------+--------------------+

In [ ]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
svclassifier = SVC(kernel='linear', degree=8)
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
tb.add_row(["Linear", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

+---------------+--------------------+--------------------+--------------------+--------------------+
|               |      Accuracy      |     Precision      |         F1         |       Recall       |
+---------------+--------------------+--------------------+--------------------+--------------------+
|   GaussianNB  | 0.6213492063492063 | 0.6947628629081618 | 0.5996090101442231 | 0.6177689510944427 |
|  BernoulliNB  | 0.8270952380952381 | 0.8283898184033166 | 0.8246061802516026 | 0.8238354941350515 |
| MultinomialNB | 0.8222698412698413 | 0.8295550165797616 | 0.8207947936585294 | 0.8190735039758186 |
|  ComplementNB | 0.7199523809523809 | 0.7501343819115547 | 0.7059257604811858 | 0.7130487776157894 |
| Random Forest | 0.942984126984127  | 0.9427272908414412 | 0.9423376144434009 | 0.942159515573975  |
|     Linear    | 0.9100158730158731 | 0.9092998861513631 | 0.9085439701293799 | 0.908504045569247  |
+---------------+--------------------+--------------------+--------------------+--------------------+

In [ ]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
tb.add_row(["(SVM)Poly", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

+---------------+--------------------+--------------------+--------------------+--------------------+
|               |      Accuracy      |     Precision      |         F1         |       Recall       |
+---------------+--------------------+--------------------+--------------------+--------------------+
|   GaussianNB  | 0.6213492063492063 | 0.6947628629081618 | 0.5996090101442231 | 0.6177689510944427 |
|  BernoulliNB  | 0.8270952380952381 | 0.8283898184033166 | 0.8246061802516026 | 0.8238354941350515 |
| MultinomialNB | 0.8222698412698413 | 0.8295550165797616 | 0.8207947936585294 | 0.8190735039758186 |
|  ComplementNB | 0.7199523809523809 | 0.7501343819115547 | 0.7059257604811858 | 0.7130487776157894 |
| Random Forest | 0.942984126984127  | 0.9427272908414412 | 0.9423376144434009 | 0.942159515573975  |
|     Linear    | 0.9100158730158731 | 0.9092998861513631 | 0.9085439701293799 | 0.908504045569247  |
|   (SVM)Poly   | 0.7293174603174604 | 0.8867951574125769 | 0.7676519752323047 | 0.7245787969098132 |
+---------------+--------------------+--------------------+--------------------+--------------------+

In [ ]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
svclassifier = SVC(kernel='sigmoid', degree=8)
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
tb.add_row(["(SVM)Sigmoid", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

+---------------+--------------------+--------------------+--------------------+--------------------+
|               |      Accuracy      |     Precision      |         F1         |       Recall       |
+---------------+--------------------+--------------------+--------------------+--------------------+
|   GaussianNB  | 0.6213492063492063 | 0.6947628629081618 | 0.5996090101442231 | 0.6177689510944427 |
|  BernoulliNB  | 0.8270952380952381 | 0.8283898184033166 | 0.8246061802516026 | 0.8238354941350515 |
| MultinomialNB | 0.8222698412698413 | 0.8295550165797616 | 0.8207947936585294 | 0.8190735039758186 |
|  ComplementNB | 0.7199523809523809 | 0.7501343819115547 | 0.7059257604811858 | 0.7130487776157894 |
| Random Forest | 0.942984126984127  | 0.9427272908414412 | 0.9423376144434009 | 0.942159515573975  |
|     Linear    | 0.9100158730158731 | 0.9092998861513631 | 0.9085439701293799 | 0.908504045569247  |
|   (SVM)Poly   | 0.7293174603174604 | 0.8867951574125769 | 0.7676519752323047 | 0.7245787969098132 |
|  (SVM)Sigmoid | 0.8275873015873015 | 0.8243653782288112 | 0.8238402716992953 | 0.8243240226893752 |
+---------------+--------------------+--------------------+--------------------+--------------------+

In [ ]:
mnist= fetch_openml('mnist_784', version=1)
x = mnist['data']
y=mnist['target']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.9, random_state = 1)
svclassifier = SVC(kernel='rbf', degree=8)
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
tb.add_row(["(SVM)RBF", accuracy_score(y_test, y_pred)
,precision_score(y_test, y_pred , average='macro',zero_division=0)
,f1_score(y_test, y_pred , average='macro',zero_division=0) 
,recall_score(y_test, y_pred , average='macro',zero_division=0) ])
tb

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(

+---------------+--------------------+--------------------+--------------------+--------------------+
|               |      Accuracy      |     Precision      |         F1         |       Recall       |
+---------------+--------------------+--------------------+--------------------+--------------------+
|   GaussianNB  | 0.6213492063492063 | 0.6947628629081618 | 0.5996090101442231 | 0.6177689510944427 |
|  BernoulliNB  | 0.8270952380952381 | 0.8283898184033166 | 0.8246061802516026 | 0.8238354941350515 |
| MultinomialNB | 0.8222698412698413 | 0.8295550165797616 | 0.8207947936585294 | 0.8190735039758186 |
|  ComplementNB | 0.7199523809523809 | 0.7501343819115547 | 0.7059257604811858 | 0.7130487776157894 |
| Random Forest | 0.942984126984127  | 0.9427272908414412 | 0.9423376144434009 | 0.942159515573975  |
|     Linear    | 0.9100158730158731 | 0.9092998861513631 | 0.9085439701293799 | 0.908504045569247  |
|   (SVM)Poly   | 0.7293174603174604 | 0.8867951574125769 | 0.7676519752323047 | 0.7245787969098132 |
|  (SVM)Sigmoid | 0.8275873015873015 | 0.8243653782288112 | 0.8238402716992953 | 0.8243240226893752 |
|    (SVM)RBF   | 0.956031746031746  | 0.9558055603107058 | 0.9556371470231391 | 0.9555596878196904 |
+---------------+--------------------+--------------------+--------------------+--------------------+

#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')

#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [18]:
data= pd.read_csv('bank.csv')
sc= StandardScaler()
data[['age', 'balance', 'day', 'campaign', 'pdays', 'previous']]=sc.fit_transform(data[['age', 'balance', 'day', 'campaign', 'pdays', 'previous']])
data

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,1.491505,admin.,married,secondary,no,0.252525,yes,no,unknown,-1.265746,may,1042,-0.554168,-0.481184,-0.363260,unknown,yes
1,1.239676,admin.,married,secondary,no,-0.459974,no,no,unknown,-1.265746,may,1467,-0.554168,-0.481184,-0.363260,unknown,yes
2,-0.019470,technician,married,secondary,no,-0.080160,yes,no,unknown,-1.265746,may,1389,-0.554168,-0.481184,-0.363260,unknown,yes
3,1.155733,services,married,secondary,no,0.293762,yes,no,unknown,-1.265746,may,579,-0.554168,-0.481184,-0.363260,unknown,yes
4,1.071790,admin.,married,tertiary,no,-0.416876,no,no,unknown,-1.265746,may,673,-0.186785,-0.481184,-0.363260,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,-0.691015,blue-collar,single,primary,no,-0.473616,yes,no,cellular,0.515650,apr,257,-0.554168,-0.481184,-0.363260,unknown,no
11158,-0.187357,services,married,secondary,no,-0.246658,no,no,unknown,0.040612,jun,83,0.547981,-0.481184,-0.363260,unknown,no
11159,-0.774958,technician,single,secondary,no,-0.464934,no,no,cellular,0.396891,aug,156,-0.186785,-0.481184,-0.363260,unknown,no
11160,0.148416,technician,married,secondary,no,-0.473926,no,yes,cellular,-0.909466,may,9,-0.186785,1.109571,1.818332,failure,no
11161,-0.607072,technician,married,secondary,no,-0.473926,no,no,cellular,-0.790707,jul,628,-0.554168,-0.481184,-0.363260,unknown,no

#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [19]:


encoder = OneHotEncoder()
encoded_data =encoder.fit_transform(data[['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']])
encoded_df = pd.DataFrame(encoded_data.toarray(), columns=encoder.get_feature_names_out(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']))
data_encoded = pd.concat([data, encoded_df], axis=1)
data_encoded.drop(columns=['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome'], inplace=True)

data_encoded

,age,balance,day,duration,campaign,pdays,previous,deposit,job_admin.,job_blue-collar,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,1.491505,0.252525,-1.265746,1042,-0.554168,-0.481184,-0.363260,yes,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.239676,-0.459974,-1.265746,1467,-0.554168,-0.481184,-0.363260,yes,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,-0.019470,-0.080160,-1.265746,1389,-0.554168,-0.481184,-0.363260,yes,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.155733,0.293762,-1.265746,579,-0.554168,-0.481184,-0.363260,yes,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.071790,-0.416876,-1.265746,673,-0.186785,-0.481184,-0.363260,yes,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,-0.691015,-0.473616,0.515650,257,-0.554168,-0.481184,-0.363260,no,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11158,-0.187357,-0.246658,0.040612,83,0.547981,-0.481184,-0.363260,no,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11159,-0.774958,-0.464934,0.396891,156,-0.186785,-0.481184,-0.363260,no,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11160,0.148416,-0.473926,-0.909466,9,-0.186785,1.109571,1.818332,no,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11161,-0.607072,-0.473926,-0.790707,628,-0.554168,-0.481184,-0.363260,no,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

#3.3. Apply **Decision tree, Random forest, kNN, Na√ØveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [20]:
tb = PrettyTable()
tb.field_names = ["","Accuracy", "Precision", "F1", "Recall"]
data_encoded['deposit']= data_encoded['deposit'].map({'yes':1, 'no':0})
data_encoded

,age,balance,day,duration,campaign,pdays,previous,deposit,job_admin.,job_blue-collar,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,1.491505,0.252525,-1.265746,1042,-0.554168,-0.481184,-0.363260,1,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.239676,-0.459974,-1.265746,1467,-0.554168,-0.481184,-0.363260,1,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,-0.019470,-0.080160,-1.265746,1389,-0.554168,-0.481184,-0.363260,1,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.155733,0.293762,-1.265746,579,-0.554168,-0.481184,-0.363260,1,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.071790,-0.416876,-1.265746,673,-0.186785,-0.481184,-0.363260,1,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,-0.691015,-0.473616,0.515650,257,-0.554168,-0.481184,-0.363260,0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11158,-0.187357,-0.246658,0.040612,83,0.547981,-0.481184,-0.363260,0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11159,-0.774958,-0.464934,0.396891,156,-0.186785,-0.481184,-0.363260,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11160,0.148416,-0.473926,-0.909466,9,-0.186785,1.109571,1.818332,0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11161,-0.607072,-0.473926,-0.790707,628,-0.554168,-0.481184,-0.363260,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [21]:

x_train, x_test, y_train, y_test = tts(data_encoded.drop(['deposit'],axis=1), data_encoded['deposit'], test_size=0.3, random_state=1)
clf = DecisionTreeClassifier(random_state=42)
clf.fit(x_train, y_train)
y_predict = clf.predict(x_test)
tb.add_row(["Tree", accuracy_score(y_test, y_predict)
,precision_score(y_test, y_predict , average='macro',zero_division=0)
,f1_score(y_test, y_predict , average='macro',zero_division=0) 
,recall_score(y_test, y_predict , average='macro',zero_division=0) ])

In [22]:
clf = BernoulliNB()
clf.fit(x_train, y_train) 
y_predict = clf.predict(x_test) 
tb.add_row(["Navie Bayes", accuracy_score(y_test, y_predict)
,precision_score(y_test, y_predict , average='macro',zero_division=0)
,f1_score(y_test, y_predict , average='macro',zero_division=0) 
,recall_score(y_test, y_predict , average='macro',zero_division=0) ])

In [23]:
clf=RandomForestClassifier() 
clf.fit(x_train,y_train) 
y_predict = clf.predict(x_test) 
tb.add_row(["Randomforest", accuracy_score(y_test, y_predict)
,precision_score(y_test, y_predict , average='macro',zero_division=0)
,f1_score(y_test, y_predict , average='macro',zero_division=0) 
,recall_score(y_test, y_predict , average='macro',zero_division=0) ])

In [24]:
acc=[]
prec =[]
recall=[]
f1=[]
k_range = range(1,8,2)
for k in k_range:
  KNN = knc(n_neighbors=k)
  KNN.fit(x_train, y_train)
  pred = KNN.predict(x_test)
  acc.append(m.accuracy_score(y_test, pred))
  prec.append(m.precision_score(y_test, pred))
  recall.append( m.recall_score(y_test, pred))
  f1.append(m.f1_score(y_test, pred))
tb.add_row(['KNN', str(round(acc[3],2)), str(round(prec[3],2)), str(round(recall[3],2)), str(round(f1[3],2))])

#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3.

#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.

In [ ]:
# code

#Finally,
Save a copy in your Github. Remember renaming the notebook.